### ISSUE TITLE
cli version?

### ISSUE THREAD

**Issue by will** [vusec/ridl#1]
It would be nice if there was a way to build this that didn't depend on X11, and printed the checks to standard out.

**Comment by genbtc** [comment]
I am working on this now.
Progress, 90% Done, checking for bugs and problems now.
EDIT: Done, see next comment .
![mdstool-CONSOLE_2019-05-14_23-23-02](https://user-images.githubusercontent.com/3683744/57746520-7c5f2a80-769f-11e9-9700-68cc44943e6c.png)

**Comment by genbtc** [comment]
The conversion process is done. [https://github.com/genBTC/ridl/](https://github.com/genBTC/ridl/)
Tested on windows above, and it's working on linux now, below:

![mdstool+Linux_2019-05-15_00-05-24](https://user-images.githubusercontent.com/3683744/57747844-415ff580-76a5-11e9-9d01-f10bdb70ae21.png)

I ran into some issues with the SSB_INFO part of the program. Will have to investigate more on that, it seems like linux queries the SSB differently than windows, and the original upstream main.c actually passes the "spectre_info" struct into the function call to "show_ssb_tab()" which is expecting a struct of "ssb_info" , which just seems weird, perhaps a bug (not unlikely, since i found other clear bugs that i submitted pull requests for). The only thing this would affect is that the "Speculative Store Bypass" and "Speculative Store Bypass Disable" would be incorrect. The rest of the spectre Direct and Indirect Branch Speculation sections are correct though, so you can base your decision on that.

**Comment by deepdad** [comment]
thank you, this works (but it does show vulnerability while I disabled hyper-threading on a Mac Pro host) for a Linux (VirtualBox) VM
On the Mac host I get (and would appreciate your help):
[100%] Linking C executable mdstool
Undefined symbols for architecture x86_64:
  "_cpuid", referenced from:
      _cpuid_get_vendor_id in cpuid.c.o
      _cpuid_get_vendor in cpuid.c.o
      _cpuid_get_brand_string in cpuid.c.o
      _amd_get_codename in cpuid.c.o
      _intel_get_codename in cpuid.c.o
      _query_ridl_info in ridl.c.o
     (maybe you meant: _cpuid_get_codename, _cpuid_has_feature , _cpuid_get_brand_string , _cpuid_get_vendor_id , _cpuid_get_vendor )
  "_cpuidex", referenced from:
      _amd_has_feature in cpuid.c.o
      _cpuid_has_feature in cpuid.c.o
  "_get_memory_size", referenced from:
      _query_sys_info in system.c.o
  "_get_microcode", referenced from:
      _query_sys_info in system.c.o
  "_get_os_name", referenced from:
      _query_sys_info in system.c.o
  "_query_l1tf_info", referenced from:
      _main in main.c.o
  "_query_meltdown_info", referenced from:
      _main in main.c.o
  "_query_spectre_info", referenced from:
      _main in main.c.o
  "_read_cpu_topology", referenced from:
      _query_ridl_info in ridl.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [mdstool] Error 1
make[1]: *** [CMakeFiles/mdstool.dir/all] Error 2
make: *** [all] Error 2

**Comment by StephanvanSchaik** [comment]
Hello all, I have just pushed a few commits that introduces `mdstool-cli`, i.e. the command line version in addition to the GUI version. Feel free to test it out. I will make sure to also build binaries of this in the next few days.

@deepdad I will hopefully have some time to work a bit on the Mac OS X and FreeBSD ports in the next few days. I haven't worked on that yet because it takes quite some work to port.

**Comment by will** [comment]
Awesome, thank you :)
